services:
  tech-blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-blog
    container_name: tech-blog
    volumes:
      - ./:/srv/jekyll
    ports:
      - "4000:4000"
    command: >
      bash -c "bundle install &&
               bundle exec jekyll serve --host 0.0.0.0 --livereload"
    environment:
      - JEKYLL_ENV=development
